import pandas as pd
from datetime import datetime
import io

def export_to_csv(analysis_text, reviews_text):
    """Export analysis to CSV format"""
    
    data = {
        'Timestamp': [datetime.now().strftime("%Y-%m-%d %H:%M:%S")],
        'Reviews': [reviews_text[:500] + "..."],  # Truncate for CSV
        'Analysis': [analysis_text]
    }
    
    df = pd.DataFrame(data)
    
    # Convert to CSV
    csv_buffer = io.StringIO()
    df.to_csv(csv_buffer, index=False)
    
    return csv_buffer.getvalue()

def export_to_excel(analysis_text, reviews_text, sentiment_data):
    """Export analysis to Excel format with multiple sheets"""
    
    output = io.BytesIO()
    
    with pd.ExcelWriter(output, engine='openpyxl') as writer:
        # Sheet 1: Summary
        summary_df = pd.DataFrame({
            'Metric': ['Analysis Date', 'Total Reviews', 'Positive %', 'Negative %'],
            'Value': [
                datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                len(reviews_text.split('\n')),
                sentiment_data['positive'],
                sentiment_data['negative']
            ]
        })
        summary_df.to_excel(writer, sheet_name='Summary', index=False)
        
        # Sheet 2: Full Analysis
        analysis_df = pd.DataFrame({
            'Analysis': [analysis_text]
        })
        analysis_df.to_excel(writer, sheet_name='Full Analysis', index=False)
        
        # Sheet 3: Reviews
        reviews_df = pd.DataFrame({
            'Review': reviews_text.split('\n')
        })
        reviews_df.to_excel(writer, sheet_name='Reviews', index=False)
    
    output.seek(0)
    return output.getvalue()

def create_markdown_report(analysis_text, reviews_text, sentiment_data):
    """Create a markdown formatted report"""
    
    report = f"""# Customer Insight Analysis Report

**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

---

## Sentiment Overview

- **Positive Sentiment:** {sentiment_data['positive']}%
- **Negative Sentiment:** {sentiment_data['negative']}%
- **Total Reviews Analyzed:** {len(reviews_text.split('\n'))}

---

## Detailed Analysis

{analysis_text}

---

## Sample Reviews
```
{reviews_text[:1000]}
```

---

## Key Metrics

| Metric | Value |
|--------|-------|
| Analysis Date | {datetime.now().strftime("%Y-%m-%d %H:%M:%S")} |
| Total Reviews | {len(reviews_text.split('\n'))} |
| Positive Sentiment | {sentiment_data['positive']}% |
| Negative Sentiment | {sentiment_data['negative']}% |
| Neutral Sentiment | {100 - sentiment_data['positive'] - sentiment_data['negative']}% |

---

## Recommendations

Based on the analysis above, consider implementing the insights provided to improve customer satisfaction and address key pain points.

---

*Report generated by Customer Insight AI - Powered by Google Gemini*

---

### Need Help?

For questions or support, contact your data analytics team.

### Resources

- [Customer Service Dashboard](#)
- [Product Feedback Portal](#)
- [Analytics Documentation](#)
"""
    
    return report

def export_to_json(analysis_text, reviews_text, sentiment_data):
    """Export analysis to JSON format"""
    import json
    
    data = {
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "summary": {
            "total_reviews": len(reviews_text.split('\n')),
            "positive_sentiment": sentiment_data['positive'],
            "negative_sentiment": sentiment_data['negative'],
            "neutral_sentiment": 100 - sentiment_data['positive'] - sentiment_data['negative']
        },
        "analysis": analysis_text,
        "reviews": reviews_text.split('\n')[:100]  # First 100 reviews
    }
    
    return json.dumps(data, indent=2)